stages:
  - build

build-job:
  stage: build
  image: node:18 # Hoặc phiên bản Node.js khác bạn đang dùng
  script:
    - npm install --global electron-builder # Cài đặt electron-builder
    - npm install
    - npm run electron:build -- --publish always
  artifacts:
    paths:
      - dist/
    expire_in: 1 week